/*
 * chinook_can_ids.h
 *
 *  Created on: May 24, 2022
 *      Author: Marc
 */

#ifndef INC_CHINOOK_CAN_IDS_H_
#define INC_CHINOOK_CAN_IDS_H_


//
// Command values shared by boards
//

// Motor modes
#define MOTOR_MODE_MANUAL 0x1
#define MOTOR_MODE_AUTOMATIC 0x2
#define MOTOR_MODE_TOGGLE 0x10

// Emergency commands
#define MOTOR_EMERGENCY_STOP_DISABLE 0x1
#define MOTOR_EMERGENCY_STOP_ENABLE 0x200
#define DRIVE_MOTOR_RESET_CMD 0x1
#define ROPS_DISABLE 0x1
#define ROPS_ENABLE 0x20

// Manual motor control
#define MOTOR_DIRECTION_STOP 0x100
#define MOTOR_DIRECTION_LEFT 0x200
#define MOTOR_DIRECTION_RIGHT 0x300

// Acquisition control command values
#define SD_CARD_ACQ_DISABLE 0x1
#define SD_CARD_ACQ_ENABLE 0x200

// Backplane command values
#define BACKPLANE_BUZZER_BEEP 0x1



//
// Mario RX CAN messages  --  0x00 -> 0x3F
//

// Mario FIFO0 - Priority

#define VOLANT_SD_CARD_ACQ_CMD 0x01

#define DRIVEMOTOR_PITCH_MODE_FEEDBACK 0x11
#define DRIVEMOTOR_MAST_MODE_FEEDBACK 0x12
#define DRIVEMOTOR_PITCH_DONE 0x13

#define DRIVEMOTOR_PITCH_FAULT_STALL 0x14
#define DRIVEMOTOR_MAST_FAULT_STALL 0x15
#define DRIVEMOTOR_ROPS_FEEDBACK 0x16

#define VOLANT_MANUAL_ROPS_CMD 0x18

// Mario FIFO1 - Low Priority

#define VOLANT_HEARTBEAT 0x21
#define BACKPLANE_HEARTBEAT 0x22
#define DRIVEMOTOR_HEARTBEAT 0x23
#define DRIVEMOTORC9_HEARTBEAT 0x24

#define DRIVEMOTOR_PITCH_BEMF 0x26
#define DRIVEMOTOR_MAST_BEMF 0x27

#define BACKPLANE_TOTAL_VOLTAGE 0x31
#define BACKPLANE_TOTAL_CURRENT 0x32
#define BACKPLANE_BOARD_VOLTAGES_1 0x33
#define BACKPLANE_BOARD_VOLTAGES_2 0x34
#define BACKPLANE_BOARD_CURRENTS_1 0x35
#define BACKPLANE_BOARD_CURRENTS_2 0x36
#define BACKPLANE_VOLANT_VOLTAGE 0x37
#define BACKPLANE_VOLANT_CURRENT 0x38
#define BACKPLANE_BOARD_SLOTS_HS 0x39
#define BACKPLANE_VOLANT_STATUS 0x3A

#define BACKPLANE_DUMMY_TRAFFIC_MARIO 0x3B

// Mario FIFO0 - Priority filter

#define MARIO_FIFO0_RX_FILTER_ID_HIGH 0x0000
#define MARIO_FIFO0_RX_FILTER_ID_LOW  0x0000
#define MARIO_FIFO0_RX_FILTER_MASK_HIGH 0xFFFF
#define MARIO_FIFO0_RX_FILTER_MASK_LOW  0xFFE0

// Mario FIFO1 - Low priority filter

#define MARIO_FIFO1_RX_FILTER_ID_HIGH 0x0000
#define MARIO_FIFO1_RX_FILTER_ID_LOW  0x0020
#define MARIO_FIFO1_RX_FILTER_MASK_HIGH 0xFFFF
#define MARIO_FIFO1_RX_FILTER_MASK_LOW  0xFFE0


//
// Volant RX CAN messages  --  0x40 -> 0x5F
//

// Volant FIFO0 - Priority

#define MARIO_PITCH_ANGLE 0x41
#define MARIO_MAST_ANGLE 0x42
#define MARIO_ROTOR_RPM 0x43
#define MARIO_WHEEL_RPM 0x44
#define MARIO_WIND_DIRECTION 0x45
#define MARIO_WIND_SPEED 0x46
#define MARIO_TORQUE 0x47
#define MARIO_LOADCELL 0x48
#define MARIO_LIMIT_SWITCH 0x49
#define MARIO_BATT_VOLTAGE 0x4A
#define MARIO_BATT_CURRENT 0x4B

#define MARIO_PITCH_MODE_FEEDBACK 0x4C
#define MARIO_MAST_MODE_FEEDBACK 0x4D
#define MARIO_ROPS_FEEDBACK 0x4E

#define MARIO_TIP_SPEED_RATIO 0x4F

// Volant FIFO0 - Priority

#define VOLANT_FIFO0_RX_FILTER_ID_HIGH 0x0000
#define VOLANT_FIFO0_RX_FILTER_ID_LOW  0x0040
#define VOLANT_FIFO0_RX_FILTER_MASK_HIGH 0xFFFF
#define VOLANT_FIFO0_RX_FILTER_MASK_LOW  0xFFF0


//
// Drive motor RX CAN messages  --  0x60 -> 0x7F
//

// Drive motor FIFO0

#define MARIO_PITCH_MODE_CMD 0x61
#define MARIO_MAST_MODE_CMD 0x62
#define MARIO_ROPS_CMD 0x63
#define MARIO_PITCH_EMERGENCY_STOP 0x64
#define MARIO_MAST_EMERGENCY_STOP 0x65
#define MARIO_DRIVE_MOTOR_RESET 0x66

#define VOLANT_PITCH_MODE_CMD 0x6A
#define VOLANT_MAST_MODE_CMD 0x6B
//#define VOLANT_MANUAL_ROPS_CMD 0x6C

// Drive motor FIFO1

#define MARIO_PITCH_MANUAL_CMD 0x71
#define MARIO_MAST_MANUAL_CMD 0x72
#define MARIO_PITCH_CMD 0x73
#define MARIO_MAST_CMD 0x74

#define MARIO_MOTOR_ROTOR_RPM 0x77

#define VOLANT_MANUAL_PITCH_CMD 0x7A
#define VOLANT_MANUAL_MAST_CMD 0x7B

#define BACKPLANE_DUMMY_TRAFFIC_DRIVE 0x7C
#define VOLANT_DUMMY_TRAFFIC_DRIVE 0x7D

// Drive motor FIFO0 filter

#define DRIVEMOTOR_FIFO0_RX_FILTER_ID_HIGH 0x0000
#define DRIVEMOTOR_FIFO0_RX_FILTER_ID_LOW  0x0060
#define DRIVEMOTOR_FIFO0_RX_FILTER_MASK_HIGH 0xFFFF
#define DRIVEMOTOR_FIFO0_RX_FILTER_MASK_LOW  0xFFF0

// Drive motor FIFO1 filter

#define DRIVEMOTOR_FIFO1_RX_FILTER_ID_HIGH 0x0000
#define DRIVEMOTOR_FIFO1_RX_FILTER_ID_LOW  0x0070
#define DRIVEMOTOR_FIFO1_RX_FILTER_MASK_HIGH 0xFFFF
#define DRIVEMOTOR_FIFO1_RX_FILTER_MASK_LOW  0xFFF0


//
// Backplane RX CAN messages  --  0x80 -> 0x9F
//

// Backplane FIFO0

#define MARIO_BUZZER_CMD 0x81

// Backplane FIFO0 filter

#define BACKPLANE_FIFO0_RX_FILTER_ID_HIGH 0x0000
#define BACKPLANE_FIFO0_RX_FILTER_ID_LOW  0x0080
#define BACKPLANE_FIFO0_RX_FILTER_MASK_HIGH 0xFFFF
#define BACKPLANE_FIFO0_RX_FILTER_MASK_LOW  0xFFF0



#endif /* INC_CHINOOK_CAN_IDS_H_ */
